/*global systemDictionary:true */
"use strict";

systemDictionary = {
    // Network Settings
    "networkSettings": {
        "en": "Network Settings",
        "de": "Netzwerkeinstellungen",
        "ru": "Сетевые настройки",
        "pt": "Configurações de rede",
        "nl": "Netwerkinstellingen",
        "fr": "Paramètres réseau",
        "it": "Impostazioni di rete",
        "es": "Configuración de red",
        "pl": "Ustawienia sieciowe",
        "zh-cn": "网络设置"
    },
    "serverSettings": {
        "en": "Server Settings",
        "de": "Server-Einstellungen",
        "ru": "Настройки сервера",
        "pt": "Configurações do servidor",
        "nl": "Serverinstellingen",
        "fr": "Paramètres du serveur",
        "it": "Impostazioni del server",
        "es": "Configuración del servidor",
        "pl": "Ustawienia serwera",
        "zh-cn": "服务器设置"
    },
    "discoverySettings": {
        "en": "Discovery Settings",
        "de": "Erkennungseinstellungen",
        "ru": "Настройки обнаружения",
        "pt": "Configurações de descoberta",
        "nl": "Ontdekkingsinstellingen",
        "fr": "Paramètres de découverte",
        "it": "Impostazioni di scoperta",
        "es": "Configuración de descubrimiento",
        "pl": "Ustawienia wykrywania",
        "zh-cn": "发现设置"
    },
    "bridgeIdentity": {
        "en": "Bridge Identity",
        "de": "Bridge-Identität",
        "ru": "Идентификация моста",
        "pt": "Identidade da ponte",
        "nl": "Bridge-identiteit",
        "fr": "Identité du pont",
        "it": "Identità del bridge",
        "es": "Identidad del puente",
        "pl": "Tożsamość mostu",
        "zh-cn": "桥接标识"
    },
    "host": {
        "en": "Server IP Address",
        "de": "Server-IP-Adresse",
        "ru": "IP-адрес сервера",
        "pt": "Endereço IP do servidor",
        "nl": "Server IP-adres",
        "fr": "Adresse IP du serveur",
        "it": "Indirizzo IP del server",
        "es": "Dirección IP del servidor",
        "pl": "Adres IP serwera",
        "zh-cn": "服务器IP地址"
    },
    "port": {
        "en": "HTTP Port",
        "de": "HTTP-Port",
        "ru": "HTTP-порт",
        "pt": "Porta HTTP",
        "nl": "HTTP-poort",
        "fr": "Port HTTP",
        "it": "Porta HTTP",
        "es": "Puerto HTTP",
        "pl": "Port HTTP",
        "zh-cn": "HTTP端口"
    },
    "discoveryHost": {
        "en": "Discovery IP Address",
        "de": "Erkennungs-IP-Adresse",
        "ru": "IP-адрес обнаружения",
        "pt": "Endereço IP de descoberta",
        "nl": "Ontdekkings-IP-adres",
        "fr": "Adresse IP de découverte",
        "it": "Indirizzo IP di scoperta",
        "es": "Dirección IP de descubrimiento",
        "pl": "Adres IP wykrywania",
        "zh-cn": "发现IP地址"
    },
    "discoveryPort": {
        "en": "Discovery Port",
        "de": "Erkennungs-Port",
        "ru": "Порт обнаружения",
        "pt": "Porta de descoberta",
        "nl": "Ontdekkingspoort",
        "fr": "Port de découverte",
        "it": "Porta di scoperta",
        "es": "Puerto de descubrimiento",
        "pl": "Port wykrywania",
        "zh-cn": "发现端口"
    },
    "httpsPort": {
        "en": "HTTPS Port (optional)",
        "de": "HTTPS-Port (optional)",
        "ru": "HTTPS-порт (необязательно)",
        "pt": "Porta HTTPS (opcional)",
        "nl": "HTTPS-poort (optioneel)",
        "fr": "Port HTTPS (optionnel)",
        "it": "Porta HTTPS (opzionale)",
        "es": "Puerto HTTPS (opcional)",
        "pl": "Port HTTPS (opcjonalnie)",
        "zh-cn": "HTTPS端口（可选）"
    },
    "mac": {
        "en": "MAC Address",
        "de": "MAC-Adresse",
        "ru": "MAC-адрес",
        "pt": "Endereço MAC",
        "nl": "MAC-adres",
        "fr": "Adresse MAC",
        "it": "Indirizzo MAC",
        "es": "Dirección MAC",
        "pl": "Adres MAC",
        "zh-cn": "MAC地址"
    },
    "upnpPort": {
        "en": "UPnP Port",
        "de": "UPnP-Port",
        "ru": "UPnP-порт",
        "pt": "Porta UPnP",
        "nl": "UPnP-poort",
        "fr": "Port UPnP",
        "it": "Porta UPnP",
        "es": "Puerto UPnP",
        "pl": "Port UPnP",
        "zh-cn": "UPnP端口"
    },
    "udn": {
        "en": "Unique Device Name (UUID)",
        "de": "Eindeutiger Gerätename (UUID)",
        "ru": "Уникальное имя устройства (UUID)",
        "pt": "Nome único do dispositivo (UUID)",
        "nl": "Unieke apparaatnaam (UUID)",
        "fr": "Nom unique de l'appareil (UUID)",
        "it": "Nome univoco del dispositivo (UUID)",
        "es": "Nombre único del dispositivo (UUID)",
        "pl": "Unikalna nazwa urządzenia (UUID)",
        "zh-cn": "唯一设备名称（UUID）"
    },

    // Device Configuration
    "deviceConfiguration": {
        "en": "Device Configuration",
        "de": "Gerätekonfiguration",
        "ru": "Конфигурация устройств",
        "pt": "Configuração de dispositivos",
        "nl": "Apparaatconfiguratie",
        "fr": "Configuration des appareils",
        "it": "Configurazione dispositivi",
        "es": "Configuración de dispositivos",
        "pl": "Konfiguracja urządzeń",
        "zh-cn": "设备配置"
    },
    "configuredDevices": {
        "en": "Configured Devices",
        "de": "Konfigurierte Geräte",
        "ru": "Настроенные устройства",
        "pt": "Dispositivos configurados",
        "nl": "Geconfigureerde apparaten",
        "fr": "Appareils configurés",
        "it": "Dispositivi configurati",
        "es": "Dispositivos configurados",
        "pl": "Skonfigurowane urządzenia",
        "zh-cn": "已配置的设备"
    },
    "deviceConfigHelp": {
        "en": "Configure virtual Hue lights by mapping ioBroker states to light properties. Click the + button to add a new device.",
        "de": "Konfigurieren Sie virtuelle Hue-Lichter, indem Sie ioBroker-Zustände auf Lichteigenschaften abbilden. Klicken Sie auf die + Schaltfläche, um ein neues Gerät hinzuzufügen.",
        "ru": "Настройте виртуальные лампы Hue, сопоставив состояния ioBroker со свойствами ламп. Нажмите кнопку +, чтобы добавить новое устройство.",
        "pt": "Configure luzes Hue virtuais mapeando estados do ioBroker para propriedades de luz. Clique no botão + para adicionar um novo dispositivo.",
        "nl": "Configureer virtuele Hue-lampen door ioBroker-staten te koppelen aan lampeigenschappen. Klik op de + knop om een nieuw apparaat toe te voegen.",
        "fr": "Configurez des lumières Hue virtuelles en mappant les états ioBroker aux propriétés des lumières. Cliquez sur le bouton + pour ajouter un nouvel appareil.",
        "it": "Configura le luci Hue virtuali mappando gli stati ioBroker alle proprietà delle luci. Fai clic sul pulsante + per aggiungere un nuovo dispositivo.",
        "es": "Configure luces Hue virtuales asignando estados de ioBroker a propiedades de luz. Haga clic en el botón + para agregar un nuevo dispositivo.",
        "pl": "Skonfiguruj wirtualne lampy Hue, mapując stany ioBroker na właściwości lamp. Kliknij przycisk +, aby dodać nowe urządzenie.",
        "zh-cn": "通过将ioBroker状态映射到灯光属性来配置虚拟Hue灯。点击+按钮添加新设备。"
    },
    "noDevicesConfigured": {
        "en": "No devices configured",
        "de": "Keine Geräte konfiguriert",
        "ru": "Устройства не настроены",
        "pt": "Nenhum dispositivo configurado",
        "nl": "Geen apparaten geconfigureerd",
        "fr": "Aucun appareil configuré",
        "it": "Nessun dispositivo configurato",
        "es": "No hay dispositivos configurados",
        "pl": "Brak skonfigurowanych urządzeń",
        "zh-cn": "未配置设备"
    },
    "clickToAddDevice": {
        "en": "Click the + button below to add your first virtual Hue light",
        "de": "Klicken Sie auf die + Schaltfläche unten, um Ihr erstes virtuelles Hue-Licht hinzuzufügen",
        "ru": "Нажмите кнопку + ниже, чтобы добавить вашу первую виртуальную лампу Hue",
        "pt": "Clique no botão + abaixo para adicionar sua primeira luz Hue virtual",
        "nl": "Klik op de + knop hieronder om uw eerste virtuele Hue-lamp toe te voegen",
        "fr": "Cliquez sur le bouton + ci-dessous pour ajouter votre première lumière Hue virtuelle",
        "it": "Fai clic sul pulsante + qui sotto per aggiungere la tua prima luce Hue virtuale",
        "es": "Haga clic en el botón + a continuación para agregar su primera luz Hue virtual",
        "pl": "Kliknij przycisk + poniżej, aby dodać swoją pierwszą wirtualną lampę Hue",
        "zh-cn": "点击下方的+按钮添加您的第一个虚拟Hue灯"
    },
    "deviceName": {
        "en": "Device Name",
        "de": "Gerätename",
        "ru": "Название устройства",
        "pt": "Nome do dispositivo",
        "nl": "Apparaatnaam",
        "fr": "Nom de l'appareil",
        "it": "Nome del dispositivo",
        "es": "Nombre del dispositivo",
        "pl": "Nazwa urządzenia",
        "zh-cn": "设备名称"
    },
    "lightType": {
        "en": "Light Type",
        "de": "Lichttyp",
        "ru": "Тип лампы",
        "pt": "Tipo de luz",
        "nl": "Lichttype",
        "fr": "Type de lumière",
        "it": "Tipo di luce",
        "es": "Tipo de luz",
        "pl": "Typ lampy",
        "zh-cn": "灯光类型"
    },
    "stateMapping": {
        "en": "State Mapping",
        "de": "Zustandszuordnung",
        "ru": "Сопоставление состояний",
        "pt": "Mapeamento de estados",
        "nl": "Statustoewijzing",
        "fr": "Mappage des états",
        "it": "Mappatura degli stati",
        "es": "Mapeo de estados",
        "pl": "Mapowanie stanów",
        "zh-cn": "状态映射"
    },
    "stateMappingHelp": {
        "en": "Map ioBroker states to Hue light properties. Use the search button to browse available states.",
        "de": "Ordnen Sie ioBroker-Zustände den Hue-Lichteigenschaften zu. Verwenden Sie die Suchschaltfläche, um verfügbare Zustände zu durchsuchen.",
        "ru": "Сопоставьте состояния ioBroker со свойствами ламп Hue. Используйте кнопку поиска для просмотра доступных состояний.",
        "pt": "Mapeie estados do ioBroker para propriedades de luz Hue. Use o botão de pesquisa para navegar pelos estados disponíveis.",
        "nl": "Wijs ioBroker-staten toe aan Hue-lampeigenschappen. Gebruik de zoekknop om beschikbare staten te doorzoeken.",
        "fr": "Mappez les états ioBroker aux propriétés des lumières Hue. Utilisez le bouton de recherche pour parcourir les états disponibles.",
        "it": "Mappa gli stati ioBroker alle proprietà delle luci Hue. Usa il pulsante di ricerca per sfogliare gli stati disponibili.",
        "es": "Asigne estados de ioBroker a propiedades de luz Hue. Use el botón de búsqueda para explorar los estados disponibles.",
        "pl": "Mapuj stany ioBroker na właściwości lamp Hue. Użyj przycisku wyszukiwania, aby przeglądać dostępne stany.",
        "zh-cn": "将ioBroker状态映射到Hue灯光属性。使用搜索按钮浏览可用状态。"
    },
    "mapped": {
        "en": "mapped",
        "de": "zugeordnet",
        "ru": "сопоставлено",
        "pt": "mapeado",
        "nl": "toegewezen",
        "fr": "mappé",
        "it": "mappato",
        "es": "mapeado",
        "pl": "zmapowane",
        "zh-cn": "已映射"
    },
    "confirmDeleteDevice": {
        "en": "Are you sure you want to delete this device?",
        "de": "Sind Sie sicher, dass Sie dieses Gerät löschen möchten?",
        "ru": "Вы уверены, что хотите удалить это устройство?",
        "pt": "Tem certeza de que deseja excluir este dispositivo?",
        "nl": "Weet u zeker dat u dit apparaat wilt verwijderen?",
        "fr": "Êtes-vous sûr de vouloir supprimer cet appareil ?",
        "it": "Sei sicuro di voler eliminare questo dispositivo?",
        "es": "¿Está seguro de que desea eliminar este dispositivo?",
        "pl": "Czy na pewno chcesz usunąć to urządzenie?",
        "zh-cn": "您确定要删除此设备吗？"
    },
    "addDevice": {
        "en": "Add Device",
        "de": "Gerät hinzufügen",
        "ru": "Добавить устройство",
        "pt": "Adicionar dispositivo",
        "nl": "Apparaat toevoegen",
        "fr": "Ajouter un appareil",
        "it": "Aggiungi dispositivo",
        "es": "Agregar dispositivo",
        "pl": "Dodaj urządzenie",
        "zh-cn": "添加设备"
    },
    "deleteDevice": {
        "en": "Delete Device",
        "de": "Gerät löschen",
        "ru": "Удалить устройство",
        "pt": "Excluir dispositivo",
        "nl": "Apparaat verwijderen",
        "fr": "Supprimer l'appareil",
        "it": "Elimina dispositivo",
        "es": "Eliminar dispositivo",
        "pl": "Usuń urządzenie",
        "zh-cn": "删除设备"
    },
    "selectState": {
        "en": "Select State",
        "de": "Zustand auswählen",
        "ru": "Выберите состояние",
        "pt": "Selecionar estado",
        "nl": "Selecteer staat",
        "fr": "Sélectionner l'état",
        "it": "Seleziona stato",
        "es": "Seleccionar estado",
        "pl": "Wybierz stan",
        "zh-cn": "选择状态"
    }
};
